### ISSUE TITLE
[PE-D][Tester E] Tag can contain only a single word

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W15-3/tp#160]
Could consider loosening the restriction on tag inputs? Currently, if the intended tag consists of multiple words, e.g. addi i/item2 q/2 d/This is a metal keychain t/cheap and good t/special sp/15.00 cp/10.00, the information pane states "Tags names should be alphanumeric". 

![Screenshot 2022-10-28 at 4.35.05 PM.png](https://raw.githubusercontent.com/zlimez/ped/main/files/13fa2089-95fa-48a0-84e0-1ac24475825b.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: zlimez/ped#2

**Comment by donljh** [comment]
#TODO
* This can be addressed in the user guide that tags are limited to one word AND/OR
* Change implementation of `addi` to reject tag inputs with > 1 word
