### ISSUE TITLE
[PE-D][Tester C] findi feature is not flexible enough 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W15-3/tp#171]
If my inventory had 3 items 
1) Flame
2) Flamethrower
3) Flame Keychain

Only 1 and 3 will be showed when I key in the command findi flame. Not sure if this is a bug but it might be better for findi to be more flexible.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Whysochong/ped#6

**Comment by donljh** [comment]
#TODO
This can be addressed in the user guide that keyword matching is word for word

**Comment by janelleljt** [comment]
I realised that this has been already addressed in the UG under point 4, might be ok to close this issue.
![image](https://user-images.githubusercontent.com/75255420/198994284-f3c1fdd3-93d8-4051-9b60-f55990ec49bf.png)

**Comment by melissaharijanto** [comment]
@janelleljt oh true! i think it should be ok then
