### ISSUE TITLE
[PE-D][Tester E] Cosmetics when one one order exists in order pane.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W15-3/tp#175]
There are these blue bars appearing after the one and only order in the order pane. Not sure if it is intended.

![Screenshot 2022-10-28 at 4.57.47 PM.png](https://raw.githubusercontent.com/zlimez/ped/main/files/1d4a16e1-88fa-47b0-84b7-99d01149e0a8.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: zlimez/ped#4

**Comment by donljh** [comment]
Duplicate issue. Refer to #153 for all details.
