### ISSUE TITLE
[PE-D][Tester B] TrackO does not respond when the user does editi and enters an empty quantity or negative quantity.

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W15-3/tp#179]
Perhaps should add error handling for this.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: JovonLim/ped#8

**Comment by donljh** [comment]
#TODO
Check `editi` implementation, and maybe the `Quantity` class implementation. System should reject with the **appropriate** error message given an invalid quantity input.
