### ISSUE TITLE
[PE-D][Tester C] UI bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W15-3/tp#181]
![image.png](https://raw.githubusercontent.com/Whysochong/ped/main/files/3fcdcfe1-6c3f-4821-90aa-9edaa833324c.png)

Bottom left of Image - a UI bug??

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Whysochong/ped#9

**Comment by donljh** [comment]
Duplicate issue. Refer to #153 for all relevant details.
