### ISSUE TITLE
[PE-D][Tester D] [UG Bugs] Update more information about deletei command

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W15-3/tp#184]
The deletei command cannot be done, if there exists uncompleted orders for item.
Please update it in UG for readers.

![Screenshot 2022-10-28 at 5.55.46 PM.png](https://raw.githubusercontent.com/myangat0343/ped/main/files/ac4586a3-d2d2-4e1f-85fd-d7b302a9015c.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: myangat0343/ped#5

**Comment by donljh** [comment]
This can be addressed in the user guide that items with active orders cannot be deleted
